export const GOOGLE_ADS_SCOPE = "https://www.googleapis.com/auth/adwords";
export const GOOGLE_ADS_API_VERSION = "v25";
export type GoogleAdsErrorCode = "not_configured" | "invalid_credentials" | "permission_denied" | "invalid_customer" | "api_not_enabled" | "rate_limited" | "timeout" | "api_error" | "database_error";
export class GoogleAdsSyncError extends Error { constructor(public readonly code: GoogleAdsErrorCode) { super(code); } }
export type ServiceAccountCredentials = { client_email: string; private_key: string; project_id?: string };
export type GoogleAdsDailyMetric = { campaignId: string; campaignName: string; campaignStatus: string; date: string; impressions: number; clicks: number; spend: number };
export function parseServiceAccountJson(value: string | undefined): ServiceAccountCredentials {
  if (!value) throw new GoogleAdsSyncError("not_configured");
  try { const parsed = JSON.parse(value) as Record<string, unknown>; if (parsed.type !== "service_account" || typeof parsed.client_email !== "string" || !parsed.client_email.includes("@") || typeof parsed.private_key !== "string" || !parsed.private_key.includes("PRIVATE KEY")) throw new Error("invalid"); return { client_email: parsed.client_email, private_key: parsed.private_key, project_id: typeof parsed.project_id === "string" ? parsed.project_id : undefined }; }
  catch (error) { if (error instanceof GoogleAdsSyncError) throw error; throw new GoogleAdsSyncError("invalid_credentials"); }
}
export function microsToCurrency(value: string | number | null | undefined): number | null { if (value === null || value === undefined || value === "") return null; const micros = Number(value); return Number.isFinite(micros) ? Math.round((micros / 1_000_000) * 1_000_000) / 1_000_000 : null; }
export function resolveCampaignKey(campaignId: string, campaignName: string, mapping: Record<string, string>): string { return mapping[campaignId]?.trim() || campaignName.trim(); }
export function parseCampaignMapping(value: string | undefined): Record<string, string> { if (!value) return {}; try { const parsed = JSON.parse(value) as Record<string, unknown>; return Object.fromEntries(Object.entries(parsed).filter(([, item]) => typeof item === "string" && item.trim()).map(([key, item]) => [key.replace(/\D/g, ""), (item as string).trim()])); } catch { throw new GoogleAdsSyncError("not_configured"); } }
export function syncDateRange(days = 3, now = new Date(), endOffsetDays = 0): { start: string; end: string; days: number } { const safeDays = Math.max(1, Math.min(30, Math.trunc(days) || 3)); const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); end.setUTCDate(end.getUTCDate() - Math.max(0, Math.trunc(endOffsetDays))); const start = new Date(end); start.setUTCDate(start.getUTCDate() - safeDays + 1); return { start: start.toISOString().slice(0, 10), end: end.toISOString().slice(0, 10), days: safeDays }; }
export function buildCampaignMetricsGaql(start: string, end: string): string { if (!/^\d{4}-\d{2}-\d{2}$/.test(start) || !/^\d{4}-\d{2}-\d{2}$/.test(end)) throw new GoogleAdsSyncError("api_error"); return `SELECT campaign.id, campaign.name, campaign.status, segments.date, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.ctr, metrics.average_cpc, metrics.average_cpm FROM campaign WHERE segments.date BETWEEN '${start}' AND '${end}'`; }
export function transformGoogleAdsResults(results: any[], mapping: Record<string, string>): GoogleAdsDailyMetric[] { return results.flatMap(result => { const campaignId = String(result.campaign?.id ?? ""); const originalName = String(result.campaign?.name ?? ""); const date = String(result.segments?.date ?? ""); if (!campaignId || !originalName || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return []; return [{ campaignId, campaignName: resolveCampaignKey(campaignId, originalName, mapping), campaignStatus: String(result.campaign?.status ?? "UNKNOWN"), date, impressions: Number(result.metrics?.impressions ?? 0), clicks: Number(result.metrics?.clicks ?? 0), spend: microsToCurrency(result.metrics?.costMicros) ?? 0 }]; }); }
export function toSyncedMetricRows(metrics: GoogleAdsDailyMetric[], currency: string) { return metrics.map(metric => ({ platform: "google" as const, campaign: metric.campaignName, metric_date: metric.date, impressions: metric.impressions, ad_clicks: metric.clicks, spend: metric.spend, currency, source_type: "synced" as const })); }
export function publicGoogleAdsError(error: unknown): { code: GoogleAdsErrorCode; message: string } { const code = error instanceof GoogleAdsSyncError ? error.code : "api_error"; const messages: Record<GoogleAdsErrorCode, string> = { not_configured: "Google Ads no está configurado", invalid_credentials: "Credenciales de Google Ads inválidas", permission_denied: "La cuenta de servicio no tiene acceso a Google Ads", invalid_customer: "Customer ID de Google Ads inválido", api_not_enabled: "Google Ads API no está habilitada", rate_limited: "Google Ads limitó temporalmente la sincronización", timeout: "Google Ads no respondió a tiempo", api_error: "Google Ads devolvió una respuesta inválida", database_error: "No se pudieron guardar las métricas" }; return { code, message: messages[code] }; }
