import type { Metadata } from "next";import LegalPage,{type LegalSection} from "@/app/_components/LegalPage";
export const metadata:Metadata={title:"Política de privacidad",description:"Conoce cómo Nasus recopila, utiliza, protege y conserva datos personales al operar nasus.lat y prestar servicios tecnológicos.",alternates:{canonical:"/privacidad"}};
const email=<a href="mailto:contacto@nasus.lat">contacto@nasus.lat</a>;
const sections:LegalSection[]=[
{id:"responsable",title:"Responsable",content:<p>Nasus es responsable del tratamiento descrito en esta política para el sitio <a href="https://nasus.lat">nasus.lat</a>. Para dudas o solicitudes relacionadas con privacidad, puedes escribir a {email}. No se identifica aquí una razón social ni un domicilio que no hayan sido formalmente definidos.</p>},
{id:"datos",title:"Datos que podemos recopilar",content:<><p>Según la forma en que interactúes con nosotros, podemos recopilar:</p><ul><li>nombre, correo, teléfono, empresa y cargo;</li><li>información que envíes voluntariamente mediante formularios, WhatsApp, correo o conversaciones comerciales;</li><li>datos necesarios para cotizar, contratar, desarrollar, integrar o dar soporte a un servicio;</li><li>datos técnicos como navegador, dispositivo, dirección IP aproximada e interacciones con el sitio;</li><li>atribución de campaña, incluyendo UTMs, referrer y fuente de adquisición.</li></ul><p>Te pedimos no compartir información sensible que no sea necesaria para la solicitud o servicio.</p></>},
{id:"finalidades",title:"Para qué usamos los datos",content:<><p>Podemos tratar la información para responder solicitudes, preparar cotizaciones y propuestas, dar seguimiento comercial, prestar servicios contratados, proporcionar soporte y mantener la relación con prospectos y clientes.</p><p>También podemos utilizarla para mejorar el sitio y nuestros productos, realizar analítica, prevenir abuso, proteger sistemas y cumplir obligaciones legales o fiscales cuando correspondan.</p></>},
{id:"proveedores",title:"Tecnologías y proveedores",content:<><p>Para operar podemos apoyarnos en proveedores de hosting, bases de datos, correo, analítica, publicidad, inteligencia artificial y mensajería. Algunos ejemplos representativos son Vercel, Supabase, Google, Meta/WhatsApp, Microsoft Clarity, Groq, Anthropic, OpenAI y Resend. La lista puede cambiar conforme evoluciona nuestra operación o cada proyecto.</p><p>No vendemos datos personales. Podemos compartir la información estrictamente necesaria con proveedores técnicos que participan en la prestación del servicio o cuando exista una obligación aplicable.</p></>},
{id:"ia",title:"Uso de inteligencia artificial",content:<p>Algunas interacciones y procesos pueden apoyarse en sistemas de inteligencia artificial para estructurar información, asistir conversaciones, generar borradores o facilitar tareas técnicas. Nasus no utiliza estos sistemas para tomar automáticamente decisiones legales, financieras, médicas o sensibles sobre una persona. Los resultados relevantes pueden requerir revisión humana.</p>},
{id:"cookies",title:"Cookies, analítica y publicidad",content:<p>El sitio puede usar cookies, almacenamiento local y tecnologías similares para recordar preferencias, medir funcionamiento, entender interacciones y evaluar campañas. Cuando están activas, herramientas de Google, Google Ads o Microsoft Clarity pueden procesar datos técnicos y de uso conforme a su propia configuración y políticas. Puedes gestionar cookies desde tu navegador; bloquearlas puede afectar algunas funciones.</p>},
{id:"transferencias",title:"Procesamiento por terceros y fuera de México",content:<p>Los proveedores tecnológicos pueden procesar o almacenar datos en infraestructura ubicada fuera de México cuando sea necesario para operar el servicio. Procuramos limitar la información compartida a la necesaria y seleccionar servicios adecuados para cada finalidad, sin afirmar marcos o certificaciones internacionales que no hayan sido revisados específicamente.</p>},
{id:"conservacion",title:"Conservación",content:<p>Conservamos los datos durante el tiempo razonablemente necesario para cumplir la finalidad para la que fueron recopilados, mantener continuidad comercial y soporte, proteger la seguridad y atender obligaciones legales, contractuales o fiscales aplicables. Los plazos pueden variar según el tipo de relación y proyecto.</p>},
{id:"derechos",title:"Derechos ARCO",content:<><p>Puedes solicitar acceso a tus datos personales, su rectificación, cancelación u oponerte a determinados tratamientos. Envía tu solicitud a {email}, describiendo el derecho que deseas ejercer y la información necesaria para identificar tu relación con Nasus.</p><p>Podremos pedir datos razonables para verificar identidad y localizar la información. La atención estará sujeta a los requisitos y excepciones legalmente aplicables.</p></>},
{id:"seguridad",title:"Seguridad",content:<p>Aplicamos medidas técnicas y organizativas razonables de acuerdo con la naturaleza de la información y nuestros servicios. Ningún sistema es completamente infalible, por lo que no podemos prometer seguridad absoluta. Si identificamos un riesgo relevante, tomaremos medidas razonables para contenerlo y atenderlo.</p>},
{id:"menores",title:"Menores de edad",content:<p>El sitio y los servicios comerciales de Nasus no están dirigidos específicamente a menores de edad. Si consideras que un menor proporcionó datos sin la autorización correspondiente, contáctanos para revisar el caso.</p>},
{id:"cambios",title:"Cambios a esta política",content:<p>Podemos actualizar esta política para reflejar cambios operativos, tecnológicos o normativos. La versión vigente se publicará en esta misma URL e indicará su fecha de última actualización.</p>},
];
export default function Page(){return <LegalPage eyebrow="LEGAL · PRIVACIDAD" title="Política de privacidad" intro="Esta política explica, de forma clara y general, cómo Nasus trata información personal al operar su sitio y prestar servicios tecnológicos." sections={sections}/>}
