import Link from "next/link";
import { notFound } from "next/navigation";
import { getWhatsAppConversation } from "@/lib/admin/whatsapp-data";
import { attributionLabel, type ConversationMode } from "@/lib/whatsapp/conversation-policy";
import ConversationActions from "./ConversationActions";
import { EmptyState } from "../../_ui/EmptyState";

const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleString("es-MX") : "—";

export default async function WhatsAppConversationPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await getWhatsAppConversation(id);
  if (!data) notFound();
  const { conversation, messages, lead, requirements, attribution } = data as any;
  const metadata = attribution?.metadata && typeof attribution.metadata === "object" ? attribution.metadata : {};
  return <div className="p-4 lg:p-8 max-w-[1500px] mx-auto font-mono">
    <div className="flex justify-between gap-4 items-start mb-5"><div><Link href="/admin/whatsapp" className="text-[10px] text-[#c4a882]">← VOLVER AL INBOX</Link><h1 className="text-xl font-bold mt-2">{lead?.nombre_contacto || lead?.nombre_empresa || "Conversación de WhatsApp"}</h1><p className="text-xs text-zinc-500 mt-1">+{conversation.numero}</p></div><div className="text-right"><span className="text-[10px] uppercase text-[#c4a882]">{conversation.mode}</span><p className="text-[9px] text-zinc-600">{conversation.status}</p></div></div>
    <div className="grid xl:grid-cols-[minmax(0,1fr)_22rem] gap-5">
      <main className="min-w-0"><section className="border border-zinc-800 rounded-xl overflow-hidden bg-zinc-950/50"><div className="max-h-[62vh] overflow-y-auto p-4 space-y-3">{messages.map((message: any, index: number) => <div key={message.id}>{(index === 0 || messages[index - 1]?.conversation_id !== message.conversation_id) && <div className="flex items-center gap-3 py-2"><span className="h-px bg-zinc-200 flex-1"/><span className="text-[9px] text-zinc-500">Conversación iniciada {formatDate(message.created_at)}</span><span className="h-px bg-zinc-200 flex-1"/></div>}<article className={`max-w-[85%] rounded-xl px-4 py-3 text-sm ${message.direccion === "entrante" ? "bg-zinc-100 border border-zinc-300 text-zinc-900" : message.sender_type === "human" ? "bg-amber-50 border border-amber-200 text-amber-900 ml-auto" : "bg-sky-50 border border-sky-200 text-sky-900 ml-auto"}`}><p className="whitespace-pre-wrap break-words">{message.contenido || "[media]"}</p><footer className={`flex gap-2 justify-end mt-2 text-[9px] ${message.direccion === "entrante" ? "text-zinc-700" : message.sender_type === "human" ? "text-amber-800" : "text-sky-800"}`}><span>{message.sender_type === "human" ? `Humano${message.admin_actor ? ` · ${message.admin_actor}` : ""}` : message.sender_type === "ai" ? "IA" : "Contacto"}</span><span>{message.delivery_status}</span><time>{formatDate(message.created_at)}</time></footer></article></div>)}{!messages.length && <EmptyState compact title="Sin mensajes" description="El historial de esta conversación aparecerá aquí." />}</div><div className="border-t border-zinc-800 p-4"><ConversationActions conversationId={conversation.conversationId} initialMode={conversation.mode as ConversationMode}/></div></section>
      <section className="border border-zinc-800 rounded-xl p-4 mt-5"><h2 className="text-[10px] tracking-widest text-zinc-500 mb-3">REQUERIMIENTOS ASOCIADOS</h2>{requirements.map((item: any) => <div key={item.id} className="border-t first:border-0 border-zinc-900 py-3 text-xs"><span className="text-[#c4a882]">{item.tipo}</span> · {item.estado} · {item.prioridad}<p className="text-zinc-500 mt-1">{item.resumen || "Sin resumen"}</p></div>)}{!requirements.length && <EmptyState compact title="Sin requerimientos" description="Los tickets asociados a esta conversación aparecerán aquí." />}<p className="text-[9px] text-zinc-700 mt-3">No existe una bitácora persistente de eventos internos del agente; no se muestran eventos inferidos.</p></section></main>
      <aside className="space-y-5"><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-[10px] tracking-widest text-zinc-500 mb-4">FICHA DEL LEAD</h2>{lead ? <dl className="space-y-3 text-xs">{[["Nombre", lead.nombre_contacto || lead.nombre_empresa], ["Teléfono", `+${lead.numero}`], ["Stage", lead.stage], ["Requiere humano", lead.requiere_humano ? "Sí" : "No"], ["Creado", formatDate(lead.created_at)], ["Última actividad", formatDate(lead.ultima_interaccion)], ["Notas / resumen", lead.resumen]].map(([label, value]) => <div key={label}><dt className="text-[9px] text-zinc-600">{label}</dt><dd className="text-zinc-300 mt-1 whitespace-pre-wrap">{value || "—"}</dd></div>)}</dl> : <p className="text-xs text-zinc-600">Esta conversación todavía no tiene lead asociado.</p>}</section>
      <section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-[10px] tracking-widest text-zinc-500 mb-4">ATRIBUCIÓN</h2>{attribution ? <div className="space-y-5 text-xs"><div><p className="text-[9px] tracking-widest text-cyan-500 mb-2">FIRST TOUCH</p>{[["Source", attributionLabel(attribution.source)], ["Medium", attribution.medium], ["Campaign", attribution.campaign], ["Content", attribution.content], ["Landing inicial", attribution.landing_path], ["Timestamp", formatDate(attribution.created_at)]].map(([label, value]) => <div key={label} className="mb-2"><span className="text-[9px] text-zinc-600 block">{label}</span><span className="text-zinc-300 break-all">{value || "—"}</span></div>)}</div><div className="border-t border-zinc-800 pt-4"><p className="text-[9px] tracking-widest text-[#c4a882] mb-2">CONVERSIÓN</p>{[["CTA exacto", metadata.cta_text], ["Ubicación CTA", metadata.cta_location], ["Página del clic", attribution.landing_path], ["Canal", "WhatsApp"], ["Acquisition event ID", lead?.acquisition_event_id]].map(([label, value]) => <div key={label} className="mb-2"><span className="text-[9px] text-zinc-600 block">{label}</span><span className="text-zinc-300 break-all">{value || "Unknown"}</span></div>)}</div></div> : <div><strong className="text-sm text-zinc-300">Unknown / Direct</strong><p className="text-[10px] text-zinc-600 mt-2">No existe atribución correlacionada; no se inventa un origen.</p><p className="text-xs text-[#c4a882] mt-3">Canal de conversión: WhatsApp</p></div>}</section></aside>
    </div>
  </div>;
}
