import Link from "next/link";
import { getAdminLeads } from "@/lib/admin/acquisition-data";
import { maskPhone } from "@/lib/acquisition/attribution";
const STAGES = ["exploring", "opportunity", "qualified", "high_intent"];
export default async function LeadsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const q = await searchParams; const stage = typeof q.stage === "string" ? q.stage : undefined; const human = q.human === "1";
  const leads = await getAdminLeads({ days: 365, stage, human });
  return <div className="p-6 lg:p-8 max-w-7xl mx-auto font-mono"><div className="flex flex-wrap justify-between gap-4 mb-6"><div><p className="text-[10px] tracking-widest text-[#c4a882]">PIPELINE</p><h1 className="text-2xl font-bold mt-1">Leads de WhatsApp</h1></div><form className="flex gap-2 text-xs"><select name="stage" defaultValue={stage ?? ""} className="bg-zinc-900 border border-zinc-800 rounded-lg px-3"><option value="">Todos los stages</option>{STAGES.map(s => <option key={s}>{s}</option>)}</select><label className="flex items-center gap-2 border border-zinc-800 rounded-lg px-3"><input type="checkbox" name="human" value="1" defaultChecked={human}/> Requiere humano</label><button className="bg-[#c4a882] text-black rounded-lg px-4">Filtrar</button></form></div><div className="overflow-x-auto border border-zinc-800 rounded-xl"><table className="w-full text-xs"><thead className="bg-zinc-900 text-zinc-500"><tr>{["Contacto", "Teléfono", "Empresa / sector", "Fuente / campaña", "Stage", "Humano", "Última interacción", "Resumen"].map(h => <th key={h} className="text-left font-normal px-3 py-3">{h}</th>)}</tr></thead><tbody>{leads.map(l => <tr key={l.id} className="border-t border-zinc-900 align-top"><td className="px-3 py-3"><Link href={`/admin/leads/${l.id}`} className="text-[#c4a882]">{l.nombre_contacto || "Sin nombre"}</Link></td><td className="px-3 py-3 text-zinc-500">{maskPhone(l.numero)}</td><td className="px-3 py-3 text-zinc-400">{l.nombre_empresa || "—"}<br/><span className="text-zinc-600">{l.sector || "—"}</span></td><td className="px-3 py-3 text-zinc-400">{l.source || "Sin atribución"}<br/><span className="text-zinc-600">{l.campaign || "—"}</span></td><td className="px-3 py-3 text-cyan-300">{l.stage}</td><td className="px-3 py-3">{l.requiere_humano ? <span className="text-yellow-400">Sí</span> : "—"}</td><td className="px-3 py-3 text-zinc-500">{new Date(l.ultima_interaccion).toLocaleString("es-MX")}</td><td className="px-3 py-3 text-zinc-500 max-w-xs">{l.resumen?.slice(0, 140) || "—"}</td></tr>)}</tbody></table>{!leads.length && <p className="text-center text-zinc-600 text-xs p-8">No hay leads para estos filtros.</p>}</div></div>;
}
