"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Button } from "./_ui/Button";
import { InlineMessage } from "./_ui/InlineMessage";
type Row = { id: string; platform: string; campaign: string; metric_date: string; impressions: number | null; ad_clicks: number | null; spend: number | null; currency: string; daily_budget: number | null; total_budget: number | null; source_type: string };
export default function CampaignMetricsForm({ rows }: { rows: Row[] }) {
  const router = useRouter(); const [status, setStatus] = useState<{ text: string; tone: "success" | "error" } | null>(null); const [editing, setEditing] = useState<Row | null>(null); const [saving, setSaving] = useState(false); const [removingId, setRemovingId] = useState<string | null>(null); const field = "bg-zinc-950 border border-zinc-800 rounded-lg px-3 py-2 text-xs min-w-0";
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setStatus(null); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/acquisition/campaign-metrics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); setSaving(false); setStatus(response.ok ? { text: "Guardado", tone: "success" } : { text: "No se pudo guardar", tone: "error" }); if (response.ok) { setEditing(null); router.refresh(); } }
  async function remove(id: string) { if (!confirm("¿Eliminar este registro manual?")) return; setRemovingId(id); const response = await fetch(`/api/admin/acquisition/campaign-metrics?id=${id}`, { method: "DELETE" }); setRemovingId(null); setStatus(response.ok ? { text: "Eliminado", tone: "success" } : { text: "No se pudo eliminar", tone: "error" }); if (response.ok) router.refresh(); }
  const manual = rows.filter(row => row.source_type === "manual");
  return <section className="border border-zinc-800 bg-zinc-900/30 rounded-xl p-3 sm:p-4"><form key={editing?.id ?? "new"} onSubmit={submit}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-3"><h2 className="text-xs tracking-widest text-zinc-400">{editing ? "EDITAR MÉTRICA MANUAL" : "CAPTURA MANUAL DIARIA"}</h2><span className="text-[10px] text-zinc-600">Vacío = desconocido · 0 = cero real</span></div><div className="grid sm:grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-2"><input required name="platform" defaultValue={editing?.platform} placeholder="Fuente (chatgpt)" className={field}/><input required name="campaign" defaultValue={editing?.campaign} placeholder="Campaña" className={field}/><input required name="metricDate" type="date" defaultValue={editing?.metric_date} className={field}/><input name="impressions" type="number" min="0" defaultValue={editing?.impressions ?? ""} placeholder="Impresiones" className={field}/><input name="adClicks" type="number" min="0" defaultValue={editing?.ad_clicks ?? ""} placeholder="Clics anuncio" className={field}/><input name="spend" type="number" min="0" step="0.01" defaultValue={editing?.spend ?? ""} placeholder="Gasto" className={field}/><input name="currency" defaultValue={editing?.currency ?? "MXN"} maxLength={3} className={field}/><input name="dailyBudget" type="number" min="0" step="0.01" defaultValue={editing?.daily_budget ?? ""} placeholder="Presupuesto diario" className={field}/><input name="totalBudget" type="number" min="0" step="0.01" defaultValue={editing?.total_budget ?? ""} placeholder="Presupuesto total" className={field}/><input type="hidden" name="sourceType" value="manual"/><Button type="submit" variant="primary" loading={saving} loadingText="Guardando…">Guardar / actualizar</Button>{editing && <Button type="button" variant="ghost" onClick={() => setEditing(null)}>Cancelar</Button>}{status && <InlineMessage tone={status.tone} compact>{status.text}</InlineMessage>}</div></form>
    {manual.length > 0 && <div className="overflow-x-auto mt-4"><table className="w-full text-[10px]"><thead className="text-zinc-600"><tr>{["Fecha", "Fuente", "Campaña", "Imp.", "Clics", "Gasto", "Moneda", "Acciones"].map(h => <th key={h} className="text-left font-normal py-2 pr-3">{h}</th>)}</tr></thead><tbody>{manual.map(row => <tr key={row.id} className="border-t border-zinc-800 text-zinc-400"><td className="py-2 pr-3">{row.metric_date}</td><td className="pr-3">{row.platform}</td><td className="pr-3">{row.campaign}</td><td className="pr-3">{row.impressions ?? "—"}</td><td className="pr-3">{row.ad_clicks ?? "—"}</td><td className="pr-3">{row.spend ?? "—"}</td><td className="pr-3">{row.currency}</td><td className="whitespace-nowrap"><Button variant="ghost" size="sm" className="mr-2" disabled={removingId !== null} onClick={() => setEditing(row)}>Editar</Button><Button variant="destructive" size="sm" disabled={removingId !== null && removingId !== row.id} loading={removingId === row.id} loadingText="Eliminando…" onClick={() => void remove(row.id)}>Eliminar</Button></td></tr>)}</tbody></table></div>}
  </section>;
}
