import Link from "next/link";
import { getAcquisitionDashboard } from "@/lib/admin/acquisition-data";
import { maskPhone, safeRate } from "@/lib/acquisition/attribution";
import { calculateCampaignEfficiency } from "@/lib/acquisition/costs";
import CampaignMetricsForm from "./CampaignMetricsForm";
import GoogleAdsSyncButton from "./GoogleAdsSyncButton";
import { ADS_SYNC_LABELS, formatMexicoCityTimestamp } from "@/lib/acquisition/sync-status";

const SOURCES = ["chatgpt", "google", "organic", "direct", "otros"];
const show = (value: number | null, suffix = "") => value === null ? "—" : `${value.toLocaleString("es-MX", { maximumFractionDigits: 2 })}${suffix}`;
const money = (value: number | null, currency: string) => value === null ? "—" : new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(value);

export default async function AdminDashboard({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const days = [1, 7, 30].includes(Number(query.days)) ? Number(query.days) : 30;
  const source = typeof query.source === "string" ? query.source : undefined; const campaign = typeof query.campaign === "string" ? query.campaign : undefined;
  const data = await getAcquisitionDashboard({ days, source, campaign });
  const funnel = [["Visitas", data.visits], ["Clic WhatsApp", data.whatsappClicks], ["Conversaciones", data.conversations], ["Leads", data.leads], ["Qualified", data.qualified], ["High intent", data.highIntent]] as const;
  const totals = calculateCampaignEfficiency({ spend: data.spend, impressions: data.impressions, adClicks: data.adClicks, visits: data.visits, whatsappClicks: data.whatsappClicks, conversations: data.conversations, leads: data.leads, qualified: data.qualified, highIntent: data.highIntent });
  const cards: [string, string, boolean][] = [["Impresiones", show(data.impressions), data.impressions === null], ["Clics anuncio", show(data.adClicks), data.adClicks === null], ["CTR", show(totals.ctr, "%"), totals.ctr === null], ["Gasto", data.currency ? money(data.spend, data.currency) : "—", data.spend === null], ["Visitas", show(data.visits), false], ["Clics WhatsApp", show(data.whatsappClicks), false], ["Conversaciones", show(data.conversations), false], ["Leads", show(data.leads), false], ["Qualified", show(data.qualified), false], ["High intent", show(data.highIntent), false]];
  return <div className="p-3 sm:p-5 lg:p-8 max-w-7xl mx-auto font-mono space-y-5 sm:space-y-7">
    <div className="flex flex-col sm:flex-row sm:flex-wrap sm:items-end justify-between gap-4"><div><p className="text-[10px] tracking-[.25em] text-[#c4a882]">NASUS / ACQUISITION</p><h1 className="text-xl sm:text-2xl font-bold text-zinc-100 mt-1">Funnel comercial</h1><p className="text-[11px] sm:text-xs text-zinc-500 mt-1">Métricas externas + owned · últimos {days} días</p></div><form className="grid grid-cols-2 sm:flex sm:flex-wrap gap-2 text-xs w-full sm:w-auto"><select name="days" defaultValue={days} className="min-w-0 bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2.5"><option value="1">Hoy</option><option value="7">7 días</option><option value="30">30 días</option></select><select name="source" defaultValue={source ?? ""} className="min-w-0 bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2.5"><option value="">Toda fuente</option>{SOURCES.map(s => <option key={s}>{s}</option>)}</select><select name="campaign" defaultValue={campaign ?? ""} className="col-span-2 min-w-0 bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2.5"><option value="">Toda campaña</option>{data.campaigns.map(c => <option key={c}>{c}</option>)}</select><button className="col-span-2 rounded-lg bg-[#c4a882] text-[#050508] px-4 py-2.5 font-bold">Aplicar</button></form></div>
    {!data.configured && <div className="border border-yellow-900/60 bg-yellow-950/20 text-yellow-300 text-xs p-3 rounded-lg">Supabase o las migraciones de adquisición aún no están configurados. El dashboard degrada sin romper WhatsApp.</div>}
    <section className="grid md:grid-cols-2 gap-3" aria-label="Estado de sincronización de Ads">{data.adsSyncStatuses.map(item => {
      const name = item.platform === "google" ? "Google Ads" : "ChatGPT Ads";
      const tone = item.status === "synced" ? "text-emerald-300 border-emerald-900/60" : item.status === "error" ? "text-red-300 border-red-900/60" : "text-yellow-300 border-yellow-900/60";
      return <article key={item.platform} className={`border bg-zinc-950 rounded-xl p-4 ${tone}`}><div className="flex items-center justify-between gap-3"><h2 className="text-xs tracking-wide text-zinc-300">{name}</h2><span className="text-[10px] uppercase tracking-wider">{ADS_SYNC_LABELS[item.status]}</span></div><p className="text-xs text-zinc-500 mt-2">Última actualización: <span className="text-zinc-300">{formatMexicoCityTimestamp(item.lastSuccessAt)}</span></p><p className="text-[9px] text-zinc-600 mt-1">Hora de Ciudad de México</p>{item.platform === "chatgpt" && item.status === "pending" && <p className="text-[10px] text-zinc-600 mt-2">Captura manual disponible; API oficial de reporting pendiente.</p>}</article>;
    })}</section>
    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 xl:grid-cols-10 gap-2">{cards.map(([label, value, unavailable]) => <div key={label} className="bg-zinc-900/60 border border-zinc-800 rounded-xl p-2.5 sm:p-3 min-h-20 sm:min-h-24"><div className="text-base sm:text-lg font-bold text-zinc-100 break-words">{value}</div><div className="text-[10px] text-zinc-500 mt-2">{label}</div>{unavailable && <div className="text-[9px] text-yellow-600 mt-1">No disponible</div>}</div>)}</div>
    <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-4 sm:gap-6"><section className="bg-zinc-950 border border-zinc-800 rounded-xl p-3 sm:p-5"><h2 className="text-xs tracking-widest text-zinc-400 mb-4 sm:mb-5">FUNNEL OWNED</h2>{funnel.map(([label, value], index) => <div key={label}><div className="flex justify-between bg-zinc-900/70 border border-zinc-800 px-3 sm:px-4 py-3 rounded-lg" style={{ marginInline: `${index * 3}px` }}><span className="text-xs text-zinc-400">{label}</span><strong>{value}</strong></div>{index < funnel.length - 1 && <div className="text-center text-[10px] text-zinc-600 py-1">↓ {safeRate(funnel[index + 1][1], value) === null ? "—" : `${safeRate(funnel[index + 1][1], value)}%`}</div>}</div>)}</section><section className="min-w-0"><div className="flex justify-between mb-3"><h2 className="text-xs tracking-widest text-zinc-400">LEADS RECIENTES</h2><Link href="/admin/leads" className="text-[10px] text-[#c4a882] whitespace-nowrap">Ver todos →</Link></div><div className="overflow-x-auto border border-zinc-800 rounded-xl"><table className="w-full min-w-[36rem] text-xs"><thead className="bg-zinc-900 text-zinc-500"><tr>{["Contacto", "Empresa", "Fuente", "Stage", "Actividad"].map(h => <th key={h} className="text-left font-normal px-3 py-2">{h}</th>)}</tr></thead><tbody>{data.recentLeads.map(l => <tr key={l.id} className="border-t border-zinc-900"><td className="px-3 py-3"><Link href={`/admin/leads/${l.id}`} className="text-zinc-200">{l.nombre_contacto || maskPhone(l.numero)}</Link></td><td className="px-3 py-3 text-zinc-500">{l.nombre_empresa || "—"}</td><td className="px-3 py-3 text-zinc-500">{l.source || "Sin atribución"}</td><td className="px-3 py-3 text-cyan-300">{l.stage}</td><td className="px-3 py-3 text-zinc-600">{new Date(l.ultima_interaccion).toLocaleDateString("es-MX")}</td></tr>)}</tbody></table>{!data.recentLeads.length && <p className="p-6 text-center text-xs text-zinc-600">Sin leads en este rango.</p>}</div></section></div>
    <section><div className="flex justify-between items-end mb-3"><div><h2 className="text-xs tracking-widest text-zinc-400">RENDIMIENTO POR CAMPAÑA</h2><p className="text-[10px] text-zinc-600 mt-1">Comparación de métricas externas y conversiones propias</p></div></div><div className="grid xl:grid-cols-2 gap-3">{data.campaignPerformance.map(p => <article key={`${p.platform}-${p.campaign}-${p.currency}`} className="border border-zinc-800 bg-zinc-950 rounded-xl p-3 sm:p-4 min-w-0"><div className="flex flex-col min-[380px]:flex-row min-[380px]:justify-between gap-2 min-[380px]:gap-3 mb-4"><div className="min-w-0"><p className="text-sm text-zinc-200 break-words">{p.platform} — {p.campaign}</p><p className="text-[10px] text-zinc-600">{p.rows.some((r: any) => r.source_type === "synced") ? "synced" : "manual"} · {p.currency}</p></div><strong className="text-[#c4a882] whitespace-nowrap">{money(p.spend, p.currency)}</strong></div><div className="grid grid-cols-2 min-[420px]:grid-cols-3 sm:grid-cols-4 xl:grid-cols-5 gap-2 text-[10px]">{[["Impresiones", p.impressions], ["Clics", p.adClicks], ["Visitas", p.visits], ["WhatsApp", p.whatsappClicks], ["Conversaciones", p.conversations], ["Leads", p.leads], ["Qualified", p.qualified], ["High intent", p.highIntent]].map(([label, value]) => <div key={label as string} className="bg-zinc-900 rounded p-2 min-w-0"><span className="text-zinc-600 block">{label}</span><b className="text-zinc-300 text-sm break-words">{show(value as number | null)}</b></div>)}</div><div className="grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-5 gap-2 mt-3 text-[10px]">{[["CPC", p.cpc], ["Costo / WhatsApp", p.costPerWhatsappClick], ["Costo / Lead", p.costPerLead], ["Costo / Qualified", p.costPerQualified], ["Costo / High intent", p.costPerHighIntent]].map(([label, value]) => <div key={label as string} className="min-w-0"><span className="text-zinc-600 block">{label}</span><b className="text-zinc-300 break-words">{money(value as number | null, p.currency)}</b></div>)}</div></article>)}{!data.campaignPerformance.length && <p className="text-xs text-zinc-600 border border-dashed border-zinc-800 rounded-xl p-4 sm:p-6">Todavía no hay métricas o eventos atribuidos por campaña.</p>}</div></section>
    <GoogleAdsSyncButton />
    <CampaignMetricsForm rows={data.manualMetricRows} />
  </div>;
}
