import Link from "next/link";
import { getAcquisitionDashboard } from "@/lib/admin/acquisition-data";
import { maskPhone, safeRate } from "@/lib/acquisition/attribution";
const SOURCES = ["chatgpt", "google", "organic", "direct", "otros"];
export default async function AdminDashboard({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const query = await searchParams; const days = [1, 7, 30].includes(Number(query.days)) ? Number(query.days) : 30;
  const source = typeof query.source === "string" ? query.source : undefined; const campaign = typeof query.campaign === "string" ? query.campaign : undefined;
  const data = await getAcquisitionDashboard({ days, source, campaign });
  const funnel = [["Visitas", data.visits], ["Clic WhatsApp", data.whatsappClicks], ["Conversaciones", data.conversations], ["Leads", data.leads], ["Qualified", data.qualified], ["High intent", data.highIntent]] as const;
  const cards = [["Impresiones", null], ["Clics anuncio", null], ["CTR", null], ["Visitas", data.visits], ["Clics WhatsApp", data.whatsappClicks], ["Conversaciones", data.conversations], ["Leads", data.leads], ["Qualified", data.qualified], ["High intent", data.highIntent]] as const;
  return <div className="p-6 lg:p-8 max-w-7xl mx-auto font-mono"><div className="flex flex-wrap items-end justify-between gap-4 mb-7"><div><p className="text-[10px] tracking-[.25em] text-[#c4a882]">NASUS / ACQUISITION</p><h1 className="text-2xl font-bold text-zinc-100 mt-1">Funnel comercial</h1><p className="text-xs text-zinc-500 mt-1">Datos propios · últimos {days} días</p></div><form className="flex flex-wrap gap-2 text-xs"><select name="days" defaultValue={days} className="bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2"><option value="1">Hoy</option><option value="7">7 días</option><option value="30">30 días</option></select><select name="source" defaultValue={source ?? ""} className="bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2"><option value="">Toda fuente</option>{SOURCES.map(s => <option key={s}>{s}</option>)}</select><select name="campaign" defaultValue={campaign ?? ""} className="bg-zinc-900 border border-zinc-800 rounded-lg px-3 py-2"><option value="">Toda campaña</option>{data.campaigns.map(c => <option key={c}>{c}</option>)}</select><button className="rounded-lg bg-[#c4a882] text-[#050508] px-4 py-2 font-bold">Aplicar</button></form></div>
  {!data.configured && <div className="mb-5 border border-yellow-900/60 bg-yellow-950/20 text-yellow-300 text-xs p-3 rounded-lg">Supabase o la migración de adquisición aún no están configurados. El dashboard degrada sin romper WhatsApp.</div>}
  <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-9 gap-2 mb-7">{cards.map(([label, value]) => <div key={label} className="bg-zinc-900/60 border border-zinc-800 rounded-xl p-3 min-h-24"><div className="text-xl font-bold text-zinc-100">{value ?? "—"}</div><div className="text-[10px] text-zinc-500 mt-2">{label}</div>{value === null && <div className="text-[9px] text-yellow-600 mt-1 leading-tight">Sincronización no configurada</div>}</div>)}</div>
  <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-6"><section className="bg-zinc-950 border border-zinc-800 rounded-xl p-5"><h2 className="text-xs tracking-widest text-zinc-400 mb-5">FUNNEL OWNED</h2>{funnel.map(([label, value], index) => <div key={label}><div className="flex justify-between bg-zinc-900/70 border border-zinc-800 px-4 py-3 rounded-lg" style={{ marginInline: `${index * 5}px` }}><span className="text-xs text-zinc-400">{label}</span><strong>{value}</strong></div>{index < funnel.length - 1 && <div className="text-center text-[10px] text-zinc-600 py-1">↓ {safeRate(funnel[index + 1][1], value) === null ? "—" : `${safeRate(funnel[index + 1][1], value)}%`}</div>}</div>)}</section><section><div className="flex justify-between mb-3"><h2 className="text-xs tracking-widest text-zinc-400">LEADS RECIENTES</h2><Link href="/admin/leads" className="text-[10px] text-[#c4a882]">Ver todos →</Link></div><div className="overflow-x-auto border border-zinc-800 rounded-xl"><table className="w-full text-xs"><thead className="bg-zinc-900 text-zinc-500"><tr>{["Contacto", "Empresa", "Fuente", "Stage", "Actividad"].map(h => <th key={h} className="text-left font-normal px-3 py-2">{h}</th>)}</tr></thead><tbody>{data.recentLeads.map(l => <tr key={l.id} className="border-t border-zinc-900"><td className="px-3 py-3"><Link href={`/admin/leads/${l.id}`} className="text-zinc-200">{l.nombre_contacto || maskPhone(l.numero)}</Link></td><td className="px-3 py-3 text-zinc-500">{l.nombre_empresa || "—"}</td><td className="px-3 py-3 text-zinc-500">{l.source || "Sin atribución"}</td><td className="px-3 py-3 text-cyan-300">{l.stage}</td><td className="px-3 py-3 text-zinc-600">{new Date(l.ultima_interaccion).toLocaleDateString("es-MX")}</td></tr>)}</tbody></table>{!data.recentLeads.length && <p className="p-6 text-center text-xs text-zinc-600">Sin leads en este rango.</p>}</div></section></div></div>;
}
