import assert from "node:assert/strict";import {readFileSync} from "node:fs";import {describe,test} from "node:test";import type {LLMResponse} from "../lib/llm/provider";import {writeProposalCopy} from "../lib/crm/proposal-agent";import {composeProposalMarkdown} from "../lib/crm/proposals";import {createGmailProvider} from "../lib/email/gmail";import {detectsProposalAcceptance} from "../lib/crm/proposal-delivery";
const snapshot={title:"CRM",scope:"API aprobada",currency:"MXN",items:[{description:"Backend",hours:10}],totals:{subtotal:10000,contingency_amount:1000,tax_amount:1760,total:12760},version:1};
const terms={validityDays:15,paymentTerms:"50/50",intellectualProperty:"Template PI",confidentiality:"Template NDA",supportMaintenance:"Template soporte",cancellation:"Template cancelación",scopeChanges:"Nueva estimación",exclusions:"Fuera de alcance",jurisdiction:null,legalApproved:false};
const copy={executiveSummary:"Resumen",deliverables:["API"],exclusions:["Hosting"],dependencies:["Accesos"],timeline:"2 semanas",nextStep:"Confirmar"};
describe("Fase 6 propuesta desde quote",()=>{
 test("draft no puede generar propuesta final",()=>assert.match(readFileSync("lib/crm/proposals.ts","utf8"),/quote\.status!=="approved"/));
 test("approved genera propuesta vinculada",()=>{const s=readFileSync("lib/crm/proposals.ts","utf8");assert.match(s,/quote_version_id:version\.id/);assert.match(s,/quote_id:quote\.id/)});
 test("usa snapshot exacto aprobado",()=>assert.match(readFileSync("lib/crm/proposals.ts","utf8"),/snapshot=version\.snapshot/));
 test("LLM no puede cambiar total",async()=>{const response:LLMResponse={content:[{type:"tool_use",id:"x",name:"redactar_propuesta_comercial",input:{executive_summary:"R",deliverables:[],exclusions:[],dependencies:[],timeline:"1 semana",next_step:"Sí",total:1}}],usage:{input_tokens:1,output_tokens:1},stop_reason:"tool_use",usedProvider:"claude"};let schema={} as Record<string,unknown>;const result=await writeProposalCopy(snapshot,{callWriter:async p=>{schema=p.tools?.[0].input_schema.properties??{};return response}});assert.equal("total" in schema,false);assert.equal("total" in result,false)});
 test("términos legales provienen del template",()=>{const md=composeProposalMarkdown({clientName:"ACME",project:"CRM",copy,snapshot,terms});assert.match(md,/Template PI/);assert.match(md,/requiere revisión humana/i)});
 test("regenerar incrementa versión",()=>assert.match(readFileSync("lib/crm/proposals.ts","utf8"),/proposalVersion=existing\?num\(existing\.proposal_version\)\+1:1/));
 test("propuesta enviada no se sobrescribe",()=>{const s=readFileSync("lib/crm/proposals.ts","utf8");assert.match(s,/\.insert\(\{contact_id:quote\.contact_id/);assert.doesNotMatch(s,/crm_proposals"\)\.upsert/)});
});
describe("Fase 7 Gmail y aceptación",()=>{
 test("Gmail registra message y thread reales",async()=>{const old={...process.env};Object.assign(process.env,{GMAIL_CLIENT_ID:"id",GMAIL_CLIENT_SECRET:"secret",GMAIL_REFRESH_TOKEN:"refresh",GMAIL_SENDER_EMAIL:"from@example.com"});let calls=0;const provider=createGmailProvider(async()=>{calls++;return new Response(JSON.stringify(calls===1?{access_token:"token"}:{id:"m1",threadId:"t1"}),{status:200})});assert.deepEqual(await provider.send({to:"to@example.com",subject:"S",text:"T",idempotencyKey:"k"}),{messageId:"m1",threadId:"t1"});process.env=old});
 test("error Gmail no produce referencia sent",async()=>{Object.assign(process.env,{GMAIL_CLIENT_ID:"id",GMAIL_CLIENT_SECRET:"secret",GMAIL_REFRESH_TOKEN:"refresh",GMAIL_SENDER_EMAIL:"from@example.com"});let calls=0;const p=createGmailProvider(async()=>new Response(JSON.stringify(++calls===1?{access_token:"t"}:{}),{status:calls===1?200:500}));await assert.rejects(()=>p.send({to:"x@y.com",subject:"S",text:"T",idempotencyKey:"k"}),/gmail_send_failed/)});
 test("retry tiene idempotency key por proposal y versión",()=>assert.match(readFileSync("lib/crm/proposal-delivery.ts","utf8"),/proposal-delivery:\$\{p\.id\}:v\$\{p\.proposal_version\}/));
 test("email inválido bloquea envío",()=>assert.match(readFileSync("lib/crm/proposal-delivery.ts","utf8"),/invalid_email/));
 test("proposal sin quote approved no se envía",()=>assert.match(readFileSync("lib/crm/proposal-delivery.ts","utf8"),/approved_quote_required/));
 test("respuesta se recupera solo por thread asociado",()=>{const s=readFileSync("lib/crm/proposal-delivery.ts","utf8");assert.match(s,/getThread\(p\.external_thread_id\)/);assert.doesNotMatch(s,/listThreads|messages\/list/)});
 test("aceptación crea suggestion y no convierte",()=>{assert.equal(detectsProposalAcceptance("Adelante, pueden iniciar"),true);const s=readFileSync("lib/crm/proposal-delivery.ts","utf8");assert.match(s,/proposal_acceptance_detected/);assert.doesNotMatch(s,/crm_convert_contact|stage:\s*"won"/)});
 test("logs y errores no exponen tokens ni destinatario",()=>{const s=readFileSync("lib/email/gmail.ts","utf8");assert.doesNotMatch(s,/console\.|access_token.*console|recipient.*console/)});
});
