import type {Metadata} from "next";import Link from "next/link";import LegalPage,{type LegalSection} from "@/app/_components/LegalPage";
export const metadata:Metadata={title:"Términos y condiciones",description:"Términos generales de uso de nasus.lat y de los servicios tecnológicos ofrecidos por Nasus.",alternates:{canonical:"/terminos"}};
const sections:LegalSection[]=[
{id:"identificacion",title:"Identificación",content:<p>Estos términos regulan de manera general el uso de <a href="https://nasus.lat">nasus.lat</a> y la relación inicial con Nasus. Puedes contactarnos en <a href="mailto:contacto@nasus.lat">contacto@nasus.lat</a>.</p>},
{id:"aceptacion",title:"Aceptación y alcance",content:<p>Al utilizar el sitio aceptas estos términos generales. Si no estás de acuerdo, debes abstenerte de usarlo. Estos términos no sustituyen una cotización, propuesta o contrato específico aceptado entre las partes.</p>},
{id:"servicios",title:"Servicios",content:<p>Nasus ofrece servicios tecnológicos que pueden incluir desarrollo web y de aplicaciones, automatización, inteligencia artificial, CRM, integraciones, consultoría y desarrollo de soluciones a medida. La disponibilidad y características dependen de cada proyecto.</p>},
{id:"propuestas",title:"Cotizaciones, propuestas y acuerdos específicos",content:<p>El alcance, precio, calendario, entregables, exclusiones y condiciones particulares se establecen en la cotización, propuesta o contrato correspondiente. En caso de contradicción, prevalecerá el documento específico aceptado entre Nasus y el cliente respecto de ese proyecto.</p>},
{id:"pagos",title:"Precios, impuestos y pagos",content:<p>Los precios varían según el alcance y complejidad. Los impuestos aplicables y las condiciones de pago se indicarán cuando corresponda en el documento comercial específico. No existe una política universal de reembolsos: cualquier condición aplicable deberá acordarse expresamente.</p>},
{id:"cambios",title:"Cambios de alcance",content:<p>Las solicitudes posteriores o trabajos no contemplados pueden requerir una nueva estimación y ajustes de precio, calendario o entregables. Nasus comunicará esos ajustes para su revisión antes de incorporarlos al proyecto.</p>},
{id:"cliente",title:"Responsabilidades del cliente",content:<p>El cliente debe proporcionar oportunamente la información, accesos, contenidos, decisiones y aprobaciones necesarios. Retrasos, datos incompletos o restricciones no informadas pueden afectar tiempos y resultados.</p>},
{id:"terceros",title:"Servicios de terceros",content:<p>Muchos proyectos dependen de plataformas, APIs, infraestructura, licencias o servicios externos. Nasus no controla sus interrupciones, cambios de precio, políticas, límites técnicos o disponibilidad. Cuando sea relevante, estas dependencias se identificarán en la propuesta o documentación del proyecto.</p>},
{id:"ia",title:"Resultados de inteligencia artificial",content:<p>Los sistemas de IA pueden producir resultados incompletos o incorrectos. Cuando su uso forme parte de un servicio, los resultados relevantes deben evaluarse según el contexto y pueden requerir revisión humana. Ningún resultado automatizado constituye por sí solo una garantía absoluta.</p>},
{id:"propiedad",title:"Propiedad intelectual",content:<p>La titularidad, licencias y derechos de uso de los entregables se definirán en el acuerdo específico de cada proyecto. Herramientas, librerías, componentes de código abierto y servicios de terceros conservan sus licencias correspondientes. Estos términos no implican una cesión universal de todo código o tecnología utilizada.</p>},
{id:"contenido",title:"Contenido del sitio",content:<p>La identidad visual, textos y materiales propios de Nasus no deben copiarse, modificarse o explotarse sin autorización, salvo los usos permitidos por la legislación aplicable. Las marcas y contenidos de terceros pertenecen a sus respectivos titulares.</p>},
{id:"disponibilidad",title:"Disponibilidad y limitaciones razonables",content:<p>Procuramos mantener el sitio y los servicios disponibles, pero no prometemos operación ininterrumpida ni ausencia total de errores. Podemos actualizar, modificar o suspender temporalmente funciones por mantenimiento, seguridad, cambios técnicos o causas externas.</p>},
{id:"uso",title:"Uso indebido",content:<><p>No debes usar el sitio o los servicios para:</p><ul><li>intentar accesos no autorizados o vulnerar medidas de seguridad;</li><li>distribuir malware, código dañino o contenido ilícito;</li><li>interferir deliberadamente con sistemas, cuentas o terceros;</li><li>abusar de APIs, automatizaciones o recursos tecnológicos.</li></ul></>},
{id:"suspension",title:"Suspensión o limitación de acceso",content:<p>Nasus puede limitar o suspender el acceso cuando detecte abuso, fraude, riesgo de seguridad, uso ilícito o afectación deliberada a sus sistemas o a terceros. Las condiciones de terminación de un proyecto se regirán por su acuerdo específico.</p>},
{id:"privacidad",title:"Privacidad",content:<p>El tratamiento general de información personal se describe en nuestra <Link href="/privacidad">Política de privacidad</Link>.</p>},
{id:"actualizaciones",title:"Cambios y contacto",content:<p>Podemos actualizar estos términos para reflejar cambios en el sitio, los servicios o la operación. La versión vigente se publicará aquí con su fecha de actualización. Para preguntas, escribe a <a href="mailto:contacto@nasus.lat">contacto@nasus.lat</a>.</p>},
];
export default function Page(){return <LegalPage eyebrow="LEGAL · TÉRMINOS" title="Términos y condiciones" intro="Estos son los términos generales del sitio y los servicios de Nasus. Los acuerdos específicos de cada proyecto se documentan por separado." sections={sections}/>}
