import Link from "next/link";
import { getQuoteDrafts } from "@/lib/crm/quotes";
import { Badge } from "../_ui/Badge";
import { EmptyState } from "../_ui/EmptyState";

type QuoteRow = { id: string; title: string; status: string; currency: string; total: number | string; revision: number; updated_at: string; whatsapp_leads: unknown };
export default async function QuotesPage() {
  const quotes = await getQuoteDrafts() as QuoteRow[];
  return <div className="p-6 lg:p-8 max-w-6xl mx-auto"><div className="flex items-center justify-between gap-4 mb-6"><div><p className="text-[10px] tracking-[.18em] text-[#8c6a3b]">COMERCIAL</p><h1 className="text-2xl font-semibold text-zinc-950">Cotizaciones</h1><p className="text-sm text-zinc-600">Drafts estructurados; ningún documento se envía desde esta vista.</p></div><Link href="/admin/cotizaciones/nueva" className="rounded-lg bg-[#8c6a3b] text-white px-4 py-2 text-xs font-semibold">Nueva cotización</Link></div>{quotes.length ? <div className="overflow-x-auto rounded-xl border border-zinc-200 bg-white"><table className="w-full text-sm"><thead className="bg-zinc-50 text-zinc-600"><tr>{["Cotización","Contacto","Estado","Total","Revisión","Actualizada"].map(label => <th key={label} className="text-left px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody>{quotes.map(quote => { const relation = quote.whatsapp_leads as Record<string, unknown> | Array<Record<string, unknown>> | null; const contact = Array.isArray(relation) ? relation[0] : relation; return <tr key={quote.id} className="border-t border-zinc-100 hover:bg-amber-50/30"><td className="px-4 py-3"><Link href={`/admin/cotizaciones/${quote.id}`} className="font-medium text-[#76582f]">{quote.title}</Link></td><td className="px-4 py-3">{String(contact?.nombre_empresa || contact?.nombre_contacto || contact?.numero || "—")}</td><td className="px-4 py-3"><Badge tone={quote.status === "approved" ? "success" : "warning"}>{quote.status === "approved" ? "Aprobada" : "Draft"}</Badge></td><td className="px-4 py-3">{quote.currency} {Number(quote.total).toLocaleString("es-MX", { minimumFractionDigits: 2 })}</td><td className="px-4 py-3">{quote.revision}</td><td className="px-4 py-3 text-zinc-500">{new Date(quote.updated_at).toLocaleString("es-MX")}</td></tr>; })}</tbody></table></div> : <EmptyState title="Aún no hay cotizaciones" description="Crea la primera cotización para estructurar módulos, esfuerzo y precio de un proyecto." action={<Link href="/admin/cotizaciones/nueva" className="rounded-lg bg-[#8c6a3b] text-white px-4 py-2 text-xs font-semibold">Nueva cotización</Link>} />}</div>;
}
