import { notFound } from "next/navigation";
import Link from "next/link";
import { getAdminLead } from "@/lib/admin/acquisition-data";
import { calculateLeadAcquisitionCosts } from "@/lib/acquisition/costs";
import { buildPublicPaymentUrl } from "@/lib/crm/payments";
import ContactDecisionActions from "./ContactDecisionActions";
import NewPaymentAction from "./NewPaymentAction";
import { Badge as StatusBadge, type BadgeTone } from "../../_ui/Badge";
import { EmptyState } from "../../_ui/EmptyState";

const PAYMENT_STATUS_LABEL: Record<string, string> = { pending: "Pendiente", paid: "Pagado", failed: "Rechazado", cancelled: "Cancelado", refunded: "Reembolsado" };
const PAYMENT_STATUS_TONE: Record<string, BadgeTone> = { pending: "warning", paid: "success", failed: "danger", cancelled: "neutral", refunded: "neutral" };
const PROPOSAL_STATUS_TONE: Record<string, BadgeTone> = { draft: "warning", sent: "info", accepted: "success", rejected: "danger", expired: "neutral" };

const date = (value: string | null) => value ? new Date(value).toLocaleString("es-MX") : "—";
const number = (value: number | null) => value === null ? "—" : value.toLocaleString("es-MX", { maximumFractionDigits: 2 });
const money = (value: number | null, currency: string | null) => value === null || !currency ? "—" : new Intl.NumberFormat("es-MX", { style: "currency", currency }).format(value);
const Badge = ({ children, tone = "observed" }: { children: React.ReactNode; tone?: "observed" | "calculated" }) => <span className={`text-[8px] tracking-widest border rounded px-1.5 py-0.5 ${tone === "observed" ? "border-cyan-900 text-cyan-500" : "border-yellow-900 text-yellow-500"}`}>{children}</span>;

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const data = await getAdminLead(id); if (!data) notFound();
  const lead: any = data.lead; const acquisition: any = data.acquisition; const attr = acquisition.attribution; const performance = acquisition.campaignPerformance;
  const paid = Boolean(attr?.campaign && !["organic", "direct", "referral"].includes(attr?.source));
  const costs = calculateLeadAcquisitionCosts({ spend: performance?.spend ?? null, adClicks: performance?.adClicks ?? null, leads: performance?.leads ?? null, qualified: performance?.qualified ?? null, highIntent: performance?.highIntent ?? null, hasPaidCampaign: paid });
  const activeProposal = data.proposals.find((proposal: any) => ["draft", "sent"].includes(proposal.status));
  const pendingSuggestion = data.suggestions.find((suggestion: any) => suggestion.status === "pending");
  const whatsappMode = data.conversations[0]?.mode ?? "ai";
  const fields = [["Lifecycle", lead.lifecycle], ["Stage", lead.stage], ["Nombre", lead.nombre_contacto], ["Teléfono", lead.numero], ["Empresa", lead.nombre_empresa], ["Sector", lead.sector], ["Responsable", lead.responsible], ["High intent", lead.high_intent_detected_at ? `Sí · ${date(lead.high_intent_detected_at)}` : "No"], ["Modo WhatsApp", whatsappMode], ["Problema", lead.problema_descrito], ["Servicio probable", lead.servicio_probable], ["Resumen vivo", lead.resumen], ["Requiere humano", lead.requiere_humano ? `Sí · ${lead.razon_handoff || "sin razón registrada"}` : "No"]];
  return <div className="p-6 lg:p-8 max-w-6xl mx-auto font-mono"><p className="text-[10px] tracking-widest text-[#c4a882]">CONTACTO / FICHA ÚNICA</p><div className="flex flex-wrap items-center justify-between gap-4 mb-6"><h1 className="text-2xl font-bold mt-1">{lead.nombre_contacto || lead.nombre_empresa || "Contacto"}</h1><ContactDecisionActions contactId={lead.id} proposalId={activeProposal?.id} lifecycle={lead.lifecycle} /></div>
    {pendingSuggestion && <section className="mb-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Recomendación pendiente</strong><p className="mt-1">{pendingSuggestion.reason}</p></section>}
    <section className="border border-zinc-800 rounded-xl p-5 mb-5"><div className="flex items-center gap-2 mb-5"><h2 className="text-xs text-zinc-400 tracking-widest">ADQUISICIÓN</h2><Badge>OBSERVADO</Badge></div>{attr ? <><div className="grid sm:grid-cols-3 lg:grid-cols-5 gap-4 text-xs">{Object.entries({ Origen: attr.source, Medio: attr.medium, Campaña: attr.campaign, Contenido: attr.content, "Attribution ID": attr.attribution_id, "First touch": date(attr.created_at), "Landing inicial": attr.landing_path, "Stage actual": lead.stage, "Primera interacción": date(acquisition.firstInteractionAt), "Última interacción": date(lead.ultima_interaccion) }).map(([key, value]) => <div key={key}><dt className="text-[10px] text-zinc-600">{key}</dt><dd className="text-zinc-300 mt-1 break-all">{String(value || "—")}</dd></div>)}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-5">{[["Sesiones atribuibles", acquisition.sessions], ["Page views", acquisition.pageViews], ["Clics WhatsApp", acquisition.whatsappClicks], ["Inició conversación", acquisition.conversationStarted ? "Sí" : "No"]].map(([label, value]) => <div key={label as string} className="bg-zinc-900 rounded-lg p-3"><span className="text-[10px] text-zinc-600 block">{label}</span><strong className="text-lg text-zinc-200">{value === null ? "—" : value}</strong></div>)}</div></> : <p className="text-xs text-zinc-600">Sin atribución web correlacionada. No se inventan visitas ni costos individuales.</p>}
      <div className="border-t border-zinc-800 mt-6 pt-5"><div className="flex items-center gap-2 mb-4"><h3 className="text-xs text-zinc-400 tracking-widest">RENDIMIENTO DE CAMPAÑA</h3><Badge tone="calculated">AGREGADO / CALCULADO</Badge></div>{performance ? <><p className="text-[10px] text-zinc-600 mb-4">Rango coherente completo: {performance.rangeStart} → {performance.rangeEnd}. Gasto, eventos y leads se limitan a esas mismas fechas.</p><div className="grid grid-cols-3 sm:grid-cols-6 gap-2 text-[10px]">{[["Gasto", money(performance.spend, performance.currency)], ["Impresiones campaña", number(performance.impressions)], ["Clics anuncio", number(performance.adClicks)], ["CPC", money(performance.cpc, performance.currency)], ["CPM", money(performance.cpm, performance.currency)], ["CTR", performance.ctr === null ? "—" : `${number(performance.ctr)}%`], ["Visitas", performance.visits], ["WhatsApp", performance.whatsappClicks], ["Conversaciones", performance.conversations], ["Leads", performance.leads], ["Qualified", performance.qualified], ["High intent", performance.highIntent]].map(([label, value]) => <div key={label as string} className="bg-zinc-900 rounded p-2"><span className="text-zinc-600 block">{label}</span><b className="text-zinc-300 text-sm">{value}</b></div>)}</div><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mt-5">{[["CPC promedio de campaña", costs.averageCampaignCpc, "PROMEDIO"], ["Costo de entrada estimado", costs.estimatedEntryCost, "ESTIMADO"], ["Costo atribuido por lead", costs.allocatedCostPerLead, "ATRIBUIDO"], ["Costo por qualified", costs.costPerQualified, "PROMEDIO"], ["Costo por high intent", costs.costPerHighIntent, "PROMEDIO"]].filter(([, value]) => value !== null).map(([label, value, badge]) => <div key={label as string} className="border border-zinc-800 rounded-lg p-3"><div className="flex justify-between gap-2"><span className="text-[10px] text-zinc-500">{label}</span><Badge tone="calculated">{badge}</Badge></div><strong className="block text-lg text-[#c4a882] mt-2">{money(value as number, performance.currency)}</strong></div>)}</div>{costs.estimatedEntryCost !== null && <p className="text-[10px] text-zinc-600 mt-3">El costo de entrada es una estimación basada en el CPC promedio de campaña; no representa el costo exacto individual de esta persona.</p>}</> : <p className="text-xs text-zinc-600">{paid ? "No hay gasto de campaña disponible; los costos permanecen desconocidos." : "No aplica / sin campaña pagada asociada."}</p>}</div>
    </section>
    <div className="grid lg:grid-cols-2 gap-5"><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">CONTEXTO COMERCIAL</h2><dl className="space-y-4">{fields.map(([key, value]) => <div key={key as string}><dt className="text-[10px] text-zinc-600">{key}</dt><dd className="text-sm text-zinc-300 mt-1 whitespace-pre-wrap">{value || "—"}</dd></div>)}</dl></section><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">REQUERIMIENTOS</h2>{data.requirements.length ? data.requirements.map((requirement: any) => <div key={requirement.id} className="border-t border-zinc-900 py-3 text-xs"><span className="text-[#c4a882]">{requirement.tipo}</span> · {requirement.estado} · {requirement.prioridad}<p className="text-zinc-500 mt-1">{requirement.resumen || "Sin resumen"}</p></div>) : <EmptyState compact title="Sin requerimientos" description="Los tickets aparecen aquí cuando el contacto pide algo específico por WhatsApp." />}</section></div>
    <div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">COTIZACIONES</h2>{data.quotes.length ? data.quotes.map((quote: any) => <a key={quote.id} href={`/admin/cotizaciones/${quote.id}`} className="block border-t border-zinc-200 py-3 text-xs hover:bg-amber-50/30"><span className="font-medium text-[#76582f]">{quote.title} · V{quote.version} rev{quote.revision}</span><p className="mt-1 flex items-center gap-2 text-zinc-600"><StatusBadge tone={quote.status === "approved" ? "success" : "warning"}>{quote.status === "approved" ? "Aprobada" : "Draft"}</StatusBadge>{quote.currency || "MXN"} {Number(quote.total).toLocaleString("es-MX")}</p></a>) : <EmptyState compact title="Sin cotizaciones" description="Crea la primera cotización para este contacto." action={<Link href="/admin/cotizaciones/nueva" className="rounded-lg bg-[#8c6a3b] text-white px-3 py-1.5 text-xs font-semibold">Nueva cotización</Link>} />}</section><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">COMERCIAL / PROPUESTAS</h2>{data.proposals.length ? data.proposals.map((proposal: any) => <div key={proposal.id} className="border-t border-zinc-200 py-3 text-xs"><a href={`/propuesta/${proposal.slug}`} target="_blank" className="font-medium text-[#76582f]">{proposal.title}</a><p className="mt-1 flex items-center gap-2 text-zinc-600"><StatusBadge tone={PROPOSAL_STATUS_TONE[proposal.status] ?? "neutral"}>{proposal.status}</StatusBadge>{proposal.value == null ? "Valor no registrado" : `${proposal.currency || "MXN"} ${Number(proposal.value).toLocaleString("es-MX")}`}</p></div>) : <EmptyState compact title="Sin propuestas" description="Se generan desde una cotización aprobada, o desde contexto libre." action={<Link href="/admin/propuestas/nueva" className="rounded-lg bg-[#8c6a3b] px-3 py-1.5 text-xs font-semibold text-white">Nueva propuesta</Link>} />}</section></div>
    <div className="grid lg:grid-cols-2 gap-5 mt-5"><section className="border border-zinc-800 rounded-xl p-5"><div className="flex items-center justify-between gap-3 mb-4"><h2 className="text-xs text-zinc-500 tracking-widest">PAGOS</h2><NewPaymentAction contactId={lead.id} /></div>{data.payments.length ? data.payments.map((payment: any) => <div key={payment.id} className="border-t border-zinc-200 py-3 text-xs"><div className="flex justify-between gap-3"><span className="font-medium text-zinc-800">{payment.description}</span><StatusBadge tone={PAYMENT_STATUS_TONE[payment.status] ?? "neutral"}>{PAYMENT_STATUS_LABEL[payment.status] || payment.status}</StatusBadge></div><p className="mt-1 text-zinc-600">{payment.currency || "MXN"} {Number(payment.amount).toLocaleString("es-MX")} · {date(payment.paid_at || payment.due_at || payment.created_at)}</p>{payment.status === "pending" && payment.public_token && <a href={buildPublicPaymentUrl(payment.public_token)} target="_blank" className="mt-1 block break-all text-[#76582f]">{buildPublicPaymentUrl(payment.public_token)}</a>}</div>) : <EmptyState compact title="Sin pagos registrados" description="Usa “+ Nuevo pago” arriba para generar el primer link de cobro." />}</section><section className="border border-zinc-800 rounded-xl p-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">ACTIVIDAD</h2><div className="max-h-96 overflow-y-auto">{data.activities.length ? data.activities.map((activity: any) => <div key={activity.id} className="border-t border-zinc-200 py-3 text-xs"><div className="flex justify-between gap-3"><strong className="text-zinc-800">{activity.event_type}</strong><span className="text-zinc-500">{activity.actor}</span></div><time className="text-[10px] text-zinc-500">{date(activity.created_at)}</time>{activity.old_value && activity.new_value && <p className="mt-1 text-zinc-600">{JSON.stringify(activity.old_value)} → {JSON.stringify(activity.new_value)}</p>}</div>) : <EmptyState compact title="Sin actividad registrada" description="Cada cambio de stage, cotización, propuesta o pago queda aquí automáticamente." />}</div></section></div>
    <section className="border border-zinc-800 rounded-xl p-5 mt-5"><h2 className="text-xs text-zinc-500 tracking-widest mb-4">WHATSAPP / HISTORIAL RECIENTE</h2><p className="mb-4 flex items-center gap-2 text-xs text-zinc-600">Modo actual: <StatusBadge tone={whatsappMode === "ai" ? "success" : whatsappMode === "human" ? "warning" : "neutral"}>{whatsappMode}</StatusBadge> · {data.conversations.length} conversación(es) históricas</p>{data.messages.length ? <div className="space-y-2">{data.messages.reverse().map((message: any) => <div key={message.id} className={`max-w-3xl rounded-lg p-3 text-xs ${message.direccion === "entrante" ? "bg-zinc-900 text-zinc-300" : "bg-cyan-950/20 text-cyan-100 ml-auto"}`}><p className="whitespace-pre-wrap">{message.contenido || "[media]"}</p><time className="text-[9px] text-zinc-600 block mt-2">{date(message.created_at)}</time></div>)}</div> : <EmptyState compact title="Sin mensajes todavía" description="El historial aparece en cuanto el contacto escriba por WhatsApp." />}</section>
  </div>;
}
