"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { calculateQuote, PRICING_CATEGORIES, type PricingCategory, type PricingProfile, type PricingUnit, type QuoteLineInput } from "@/lib/crm/pricing";
import { Button } from "../../_ui/Button";

type StoredLine = { id: string; category: PricingCategory; description: string; unit: PricingUnit; quantity: number | string; hours: number | string; unit_rate: number | string; direct_cost: number | string; external_cost: number | string; margin_pct: number | string; notes: string | null };
type Review = { findings: string[]; risks: string[]; missing_requirements: string[]; recommendations: string[]; reviewer_provider: string; reviewed_at: string; trigger_reasons: string[] } | null;
type ApprovedVersion = { id: string; version: number; approved_at: string; approved_by: string; total: number | string; snapshot: Record<string, unknown> };
type InitialQuote = { id: string; title: string; scope: string; notes: string | null; currency: string; status: "draft" | "approved"; revision: number; version: number; approved_at: string | null; approved_by: string | null; pricing_snapshot: PricingProfile; risks: string[]; missing_requirements: string[]; review: Review; approved_versions: ApprovedVersion[]; items: StoredLine[]; whatsapp_leads: unknown };
type LinkedProposal = { id: string; status: string; ready_for_delivery: boolean; sent_at: string | null } | null;
const n = (value: number | string) => Number(value);
const money = (value: number) => value.toLocaleString("es-MX", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

function InsightList({ title, items, tone }: { title: string; items: string[]; tone: "amber" | "red" | "blue" | "green" }) {
  if (!items.length) return null;
  const colors = { amber: "border-amber-200 bg-amber-50", red: "border-red-200 bg-red-50", blue: "border-blue-200 bg-blue-50", green: "border-emerald-200 bg-emerald-50" };
  return <section className={`min-w-0 rounded-xl border p-4 text-sm ${colors[tone]}`}><h3 className="font-semibold text-zinc-900">{title}</h3><ul className="mt-2 list-disc space-y-1.5 pl-5 text-zinc-700">{items.map((item, index) => <li key={`${title}-${index}`} className="break-words leading-5">{item}</li>)}</ul></section>;
}

function ProposalStatus({ proposal, quoteVersion, onGenerate, busy }: { proposal: LinkedProposal; quoteVersion: number; onGenerate: () => void; busy: boolean }) {
  const router = useRouter();
  const [syncing, setSyncing] = useState(false);
  const [syncMessage, setSyncMessage] = useState("");
  if (!proposal) return <Button variant="primary" onClick={onGenerate} loading={busy} loadingText="Generando…" className="mb-4">Generar propuesta desde Quote V{quoteVersion}</Button>;
  if (proposal.status === "draft" && !proposal.ready_for_delivery) return <Button variant="secondary" onClick={() => router.push(`/admin/propuestas/${proposal.id}`)} className="mb-4">Continuar edición de la propuesta</Button>;
  if (proposal.status === "draft" && proposal.ready_for_delivery) return <Button variant="primary" onClick={() => router.push(`/admin/propuestas/${proposal.id}`)} className="mb-4">Revisar y enviar propuesta</Button>;
  async function reviewReply() { setSyncing(true); setSyncMessage(""); const response = await fetch(`/api/admin/propuestas/${proposal!.id}/sync-thread`, { method: "POST" }); const result = await response.json() as { ok?: boolean; error?: string; acceptanceDetected?: boolean }; setSyncing(false); setSyncMessage(result.ok ? (result.acceptanceDetected ? "Posible aceptación detectada; se creó una sugerencia." : "Sin señales nuevas en el hilo.") : (result.error || "Error")); router.refresh(); }
  return <div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-2.5 text-sm text-emerald-900"><span>Propuesta enviada por Gmail{proposal.sent_at ? ` el ${new Date(proposal.sent_at).toLocaleString("es-MX")}` : ""}.</span><Button variant="secondary" size="sm" onClick={() => router.push(`/admin/propuestas/${proposal!.id}`)}>Ver propuesta</Button><Button variant="secondary" size="sm" onClick={reviewReply} loading={syncing} loadingText="Revisando…">Revisar respuesta</Button>{syncMessage && <span className="w-full text-xs text-emerald-700">{syncMessage}</span>}</div>;
}

export default function QuoteEditor({ initial, linkedProposal }: { initial: InitialQuote; linkedProposal: LinkedProposal }) {
  const router = useRouter();
  const editable = initial.status === "draft";
  const [title, setTitle] = useState(initial.title);
  const [scope, setScope] = useState(initial.scope);
  const [notes, setNotes] = useState(initial.notes ?? "");
  const [revision, setRevision] = useState(initial.revision);
  const [lines, setLines] = useState<QuoteLineInput[]>(initial.items.map(item => ({ id: item.id, category: item.category, description: item.description, unit: item.unit, quantity: n(item.quantity), hours: n(item.hours), unitRate: n(item.unit_rate), directCost: n(item.direct_cost), externalCost: n(item.external_cost), marginPct: n(item.margin_pct), notes: item.notes ?? "", source: "human" })));
  const [action, setAction] = useState<null | "save" | "approve" | "revision" | "proposal">(null);
  const busy = action !== null;
  const [message, setMessage] = useState("");
  const calculation = useMemo(() => { try { return calculateQuote(lines, initial.pricing_snapshot); } catch { return null; } }, [lines, initial.pricing_snapshot]);
  const update = (index: number, patch: Partial<QuoteLineInput>) => setLines(current => current.map((line, position) => position === index ? { ...line, ...patch } : line));
  function changeCategory(index: number, category: PricingCategory) { const rate = initial.pricing_snapshot.rates.find(item => item.category === category); if (!rate || rate.rate === null) return update(index, { category }); update(index, { category, unit: rate.unit, unitRate: rate.rate, marginPct: rate.marginPct, quantity: rate.unit === "hour" ? 0 : 1, hours: rate.unit === "hour" ? lines[index].hours : 0 }); }
  function add() { const rate = initial.pricing_snapshot.rates.find(item => item.rate !== null); if (!rate || rate.rate === null) return; setLines(current => [...current, { category: rate.category, description: "Nueva partida", unit: rate.unit, quantity: rate.unit === "hour" ? 0 : 1, hours: 0, unitRate: rate.rate!, directCost: 0, externalCost: 0, marginPct: rate.marginPct, source: "human" }]); }
  async function request(body: Record<string, unknown>, method: "PATCH" | "POST") { setMessage(""); const response = await fetch(`/api/admin/quotes/${initial.id}`, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { ok?: boolean; revision?: number; quoteId?: string; error?: string }; if (!response.ok || !result.ok) { setMessage(result.error || "No se pudo completar la acción."); return null; } return result; }
  async function save() { setAction("save"); const result = await request({ expectedRevision: revision, title, scope, notes, lines }, "PATCH"); setAction(null); if (result?.revision) { setRevision(result.revision); setMessage("Draft editado y recalculado."); router.refresh(); } }
  async function approve() { if (!window.confirm("¿Aprobar esta versión? Se recalculará en el servidor y el snapshot será inmutable.")) return; setAction("approve"); const result = await request({ action: "approve", expectedRevision: revision }, "POST"); setAction(null); if (result) { setMessage("Cotización aprobada."); router.refresh(); } }
  async function createRevision() { setAction("revision"); const result = await request({ action: "create_revision" }, "POST"); if (result?.quoteId) router.push(`/admin/cotizaciones/${result.quoteId}`); else setAction(null); }
  async function createProposal() { setAction("proposal"); setMessage(""); const response = await fetch("/api/admin/propuestas/from-quote", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ quoteId: initial.id }) }); const result = await response.json() as { ok?: boolean; proposal?: { id: string }; error?: string }; if (response.ok && result.ok && result.proposal?.id) router.push(`/admin/propuestas/${result.proposal.id}`); else { setAction(null); setMessage(result.error || "No se pudo generar la propuesta."); } }
  const relation = initial.whatsapp_leads as Record<string, unknown> | Array<Record<string, unknown>> | null;
  const contact = Array.isArray(relation) ? relation[0] : relation;

  return <div className="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">
    <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
      <div className="min-w-0"><p className="text-[10px] tracking-[.18em] text-[#8c6a3b]">COTIZACIÓN · V{initial.version} · REV {revision}</p><input value={title} disabled={!editable} onChange={event => setTitle(event.target.value)} className="mt-1 w-full border-b border-transparent bg-transparent text-2xl font-semibold text-zinc-950 outline-none focus:border-zinc-300 disabled:opacity-100" /><p className="mt-1 text-sm text-zinc-500">{String(contact?.nombre_empresa || contact?.nombre_contacto || contact?.numero || "Contacto CRM")}</p></div>
      <div className="shrink-0 sm:text-right"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${editable ? "bg-amber-100 text-amber-800" : "bg-emerald-100 text-emerald-800"}`}>{editable ? "Draft" : "Aprobada"}</span><strong className="mt-2 block text-2xl text-zinc-950">{initial.currency} {money(calculation?.total ?? 0)}</strong><p className="text-xs text-zinc-500">Total determinista</p></div>
    </div>
    {!editable && <ProposalStatus proposal={linkedProposal} quoteVersion={initial.version} onGenerate={createProposal} busy={action === "proposal"} />}
    <div className="grid min-w-0 grid-cols-1 gap-6 xl:grid-cols-[minmax(0,1.85fr)_minmax(20rem,1fr)]">
      <main className="min-w-0"><label className="text-xs font-medium text-zinc-600">Alcance aprobado/propuesto<textarea value={scope} disabled={!editable} onChange={event => setScope(event.target.value)} rows={6} className="mb-4 mt-1 w-full rounded-lg border border-zinc-300 bg-white p-3 text-sm disabled:bg-zinc-50" /></label>
        <div className="w-full overflow-x-auto rounded-xl border border-zinc-200 bg-white"><table className="w-full min-w-[1080px] text-xs"><thead className="bg-zinc-50 text-zinc-700"><tr>{["Categoría / partida", "Horas", "Cantidad", "Tarifa", "Costo directo", "Costo externo", "Margen %", "Subtotal", "Acción"].map(item => <th key={item} scope="col" className="whitespace-nowrap px-3 py-3 text-left font-semibold">{item}</th>)}</tr></thead><tbody>{lines.map((line, index) => <tr key={line.id ?? index} className="border-t border-zinc-100 align-top"><td className="min-w-56 px-3 py-2"><select disabled={!editable} value={line.category} onChange={event => changeCategory(index, event.target.value as PricingCategory)} className="w-full rounded border px-2 py-1">{PRICING_CATEGORIES.map(category => <option key={category}>{category}</option>)}</select><input disabled={!editable} aria-label="Descripción de partida" value={line.description} onChange={event => update(index, { description: event.target.value })} className="mt-1 w-full rounded border px-2 py-1" /></td>{(["hours", "quantity", "unitRate", "directCost", "externalCost", "marginPct"] as const).map(field => <td key={field} className="px-3 py-2"><input type="number" min="0" step="0.01" value={line[field]} onChange={event => update(index, { [field]: Number(event.target.value) })} className="w-24 rounded border px-2 py-1" disabled={!editable || (field === "hours" && line.unit !== "hour") || (field === "quantity" && line.unit === "hour")} /></td>)}<td className="whitespace-nowrap px-3 py-3 font-semibold">{money(calculation?.lines[index]?.lineSubtotal ?? 0)}</td><td className="px-3 py-3">{editable && <Button variant="destructive" size="sm" onClick={() => setLines(current => current.filter((_, position) => position !== index))}>Quitar</Button>}</td></tr>)}</tbody></table></div>
        {editable && <Button variant="secondary" size="sm" onClick={add} className="mt-3">Agregar partida</Button>}
        <label className="mt-4 block text-xs font-medium text-zinc-600">Notas<textarea value={notes} disabled={!editable} onChange={event => setNotes(event.target.value)} rows={3} className="mt-1 w-full rounded-lg border border-zinc-300 bg-white p-3 text-sm disabled:bg-zinc-50" /></label>
      </main>
      <aside className="min-w-0 space-y-4">
        <section className="rounded-xl border border-zinc-200 bg-white p-4 text-sm"><h2 className="mb-3 font-semibold">Cálculo</h2>{calculation ? Object.entries({ "Costo directo": calculation.directCost, "Costo externo": calculation.externalCost, "Margen": calculation.marginAmount, "Contingencia": calculation.contingencyAmount, "Subtotal": calculation.subtotal, [initial.pricing_snapshot.taxLabel]: calculation.taxAmount, "Total": calculation.total }).map(([label, value]) => <div key={label} className={`flex justify-between gap-4 py-1 ${label === "Total" ? "mt-2 border-t pt-3 font-semibold" : ""}`}><span className="text-zinc-500">{label}</span><span className="whitespace-nowrap">{money(Number(value))}</span></div>) : <p className="text-red-700">Corrige los valores de las partidas.</p>}</section>
        <InsightList title="Información faltante" items={initial.missing_requirements} tone="amber" /><InsightList title="Riesgos iniciales" items={initial.risks} tone="red" />
        {initial.review && <section className="min-w-0 space-y-3 rounded-xl border border-indigo-200 bg-indigo-50/60 p-4"><div><h2 className="font-semibold text-zinc-900">Revisión Claude</h2><p className="mt-1 break-words text-xs text-zinc-500">{new Date(initial.review.reviewed_at).toLocaleString("es-MX")} · {initial.review.trigger_reasons.join(", ")}</p></div><InsightList title="Hallazgos" items={initial.review.findings} tone="blue" /><InsightList title="Riesgos del reviewer" items={initial.review.risks} tone="red" /><InsightList title="Requisitos omitidos" items={initial.review.missing_requirements} tone="amber" /><InsightList title="Recomendaciones" items={initial.review.recommendations} tone="green" /></section>}
        {editable ? <><Button variant="secondary" size="lg" fullWidth onClick={save} disabled={busy || !calculation} loading={action === "save"} loadingText="Guardando…">Guardar y recalcular</Button><Button variant="primary" size="lg" fullWidth onClick={approve} disabled={busy || !calculation} loading={action === "approve"} loadingText="Aprobando…">Aprobar cotización</Button><p className="text-[11px] leading-4 text-zinc-500">La aprobación recalcula en backend y crea un snapshot inmutable.</p></> : <><section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm"><strong>Aprobada</strong><p className="mt-1 text-zinc-600">{initial.approved_at ? new Date(initial.approved_at).toLocaleString("es-MX") : ""} · {initial.approved_by}</p></section><Button variant="secondary" size="lg" fullWidth onClick={createRevision} disabled={busy} loading={action === "revision"} loadingText="Creando…">Crear nueva versión draft</Button></>}
        {initial.approved_versions.length > 0 && <section className="rounded-xl border border-zinc-200 bg-white p-4"><h2 className="font-semibold">Historial aprobado</h2><div className="mt-2 space-y-2 text-xs">{initial.approved_versions.map(version => <div key={version.id} className="flex justify-between gap-3 rounded-lg bg-zinc-50 p-2"><span>V{version.version} · {new Date(version.approved_at).toLocaleDateString("es-MX")}</span><strong>{initial.currency} {money(Number(version.total))}</strong></div>)}</div></section>}
        {message && <p role="status" className="break-words text-xs text-zinc-600">{message}</p>}
      </aside>
    </div>
  </div>;
}
