"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "../../_ui/Button";
import { InlineMessage } from "../../_ui/InlineMessage";
export default function NewQuoteForm({ contacts }: { contacts: Array<{ id: string; name: string }> }) {
  const router = useRouter(); const [contactId, setContactId] = useState(""); const [scope, setScope] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function generate() { setBusy(true); setError(""); const response = await fetch("/api/admin/quotes/generate", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contactId, scope, requestKey: crypto.randomUUID() }) }); const result = await response.json() as { quoteId?: string; error?: string }; setBusy(false); if (response.ok && result.quoteId) router.push(`/admin/cotizaciones/${result.quoteId}`); else setError(result.error || "No se pudo crear la cotización"); }
  return <div className="p-6 lg:p-8 max-w-3xl mx-auto"><p className="text-[10px] tracking-[.18em] text-[#8c6a3b]">NUEVO DRAFT</p><h1 className="text-2xl font-semibold text-zinc-950 mb-2">Cotización desde alcance</h1><p className="text-sm text-zinc-600 mb-6">La IA estructura módulos y esfuerzo. Los precios se calculan con la configuración activa.</p><div className="rounded-xl border border-zinc-200 bg-white p-5 space-y-4"><label className="block text-sm text-zinc-700">Contacto CRM<select value={contactId} onChange={event => setContactId(event.target.value)} className="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"><option value="">Selecciona un contacto</option>{contacts.map(contact => <option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></label><label className="block text-sm text-zinc-700">Alcance<textarea value={scope} onChange={event => setScope(event.target.value)} rows={8} className="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2" placeholder="Describe objetivos, módulos, integraciones, volumen y restricciones conocidas." /></label>{error && <InlineMessage tone="error">{error}</InlineMessage>}<Button variant="primary" size="lg" onClick={generate} disabled={busy || !contactId || scope.trim().length < 10} loading={busy} loadingText="Estructurando…">Crear quote draft</Button></div></div>;
}
